##########################################################
###############          Mainnet                 #########
############### Cardano Byron Node Configuration #########
##########################################################


##### Locations #####

ByronGenesisFile: genesis/byron/genesis.json
ByronGenesisHash: 6b91f3c3d68ebeaa8dede86ba371a56ae60547dec6a8713d1fca6e403caa4605
ShelleyGenesisFile: genesis/shelley/genesis.json
ShelleyGenesisHash: 4fad52e08057e9cbfe71411719205c14c2e61e4dd4123541d0b6fa92971c89b0
AlonzoGenesisFile: genesis/shelley/genesis.alonzo.json
AlonzoGenesisHash: 1cd94b66eade0670885744a858accdb2c3249e43e247db2c66b158050ec6a3e4
ConwayGenesisFile: genesis/shelley/genesis.conway.json
ConwayGenesisHash: 01649daebfc1ae5646c6aab2bf07533cdf626fd49e270ac4258be7fe253c3cc1
SocketPath: db/node.socket

##### Blockfetch Protocol
PBftSignatureThreshold: 0.6

# The maximum number of used peers during bulk sync.
MaxConcurrencyBulkSync: 1
# The maximum number of used peers when fetching newly forged blocks.
MaxConcurrencyDeadline: 2

#TODO: These parameters cannot yet be used in the config file, only on the CLI:
#DatabasePath: db/
#Topology: configuration/mainnet-topology.json
#Port 7776

##### Core protocol parameters #####

# This is the instance of the Ouroboros family that we are running.
# "RealPBFT" is the real (permissive) OBFT protocol, which is what we use on
# mainnet in Byron era.
Protocol: Cardano

# The mainnet does not include the network magic into addresses. Testnets do.
RequiresNetworkMagic: RequiresNoMagic


##### Update system parameters #####

# This protocol version number gets used by block producing nodes as part
# of the system for agreeing on and synchronising protocol updates.
LastKnownBlockVersion-Major: 7
LastKnownBlockVersion-Minor: 0
LastKnownBlockVersion-Alt: 0
MaxKnownMajorProtocolVersion: 7
##### Logging configuration #####

# Enable or disable logging overall
TurnOnLogging: True

# Enable the collection of various OS metrics such as memory and CPU use.
# These metrics are traced in the context name: 'cardano.node.metrics' and can
# be directed to the logs or monitoring backends.
TurnOnLogMetrics: True

# Global logging severity filter. Messages must have at least this severity to
# pass. Typical values would be Warning, Notice, Info or Debug.
minSeverity: Debug

# Log items can be rendered with more or less verbose detail.
# Verbosity ranges from MinimalVerbosity, NormalVerbosity to MaximalVerbosity
TracingVerbosity: NormalVerbosity

# The system supports a number of backends for logging and monitoring.
# This setting lists the backends that will be available to use in the
# configuration below. The logging backend is called Katip.
setupBackends:
  - KatipBK

# This specifies the default backends that trace output is sent to if it
# is not specifically configured to be sent to other backends.
defaultBackends:
  - KatipBK

# EKG is a simple metrics monitoring system. Uncomment the following to enable
# this backend and listen on the given local port and point your web browser to
# http://localhost:12788/
hasEKG: 12788

# The Prometheus monitoring system exports EKG metrics. Uncomment the following
# to listen on the given port. Output is provided on
# http://localhost:12789/metrics
hasPrometheus:
  - "0.0.0.0"
  - 12789

# To enable the legacy 'TraceForwarder' backend, uncomment the following setting. Log
# items are then forwarded based on an entry in 'mapBackends' to a separate
# process running a 'TraceAcceptor'.
# Example using UNIX pipes:
# traceForwardTo:
#   tag: RemotePipe
#   contents: "logs/pipe"
#
# Example using Windows named pipes:
# traceForwardTo:
#   tag: RemotePipe
#   contents: "\\\\.\\pipe\\acceptor"
#
# Example using network socket:
# traceForwardTo:
#   tag: RemoteSocket
#   contents:
#     - "127.0.0.1"
#     - "2997"

# For the Katip logging backend we must set up outputs (called scribes)
# The available types of scribe are:
#   FileSK for files
#   StdoutSK/StderrSK for stdout/stderr
#   JournalSK for systemd's journal system
#   DevNullSK ignores all output
# The scribe output format can be ScText or ScJson. Log rotation settings can
# be specified in the defaults below or overridden on a per-scribe basis here.
setupScribes:
#  - scKind: FileSK
#    scName: "logs/mainnet.log"
#    scFormat: ScText

  - scKind: StdoutSK
    scName: stdout
    scFormat: ScText

# For the Katip logging backend this specifies the default scribes that trace
# output is sent to if it is not configured to be sent to other scribes.
defaultScribes:
#  - - FileSK
#    - "logs/mainnet.log"
  - - StdoutSK
    - stdout

# The default file rotation settings for katip scribes, unless overridden
# in the setupScribes above for specific scribes.
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  3
  rpMaxAgeHours:   24


##### Coarse grained logging control #####

# Trace output from whole subsystems can be enabled/disabled using the following
# settings. This provides fairly coarse grained control, but it is relatively
# efficient at filtering out unwanted trace output.

# Trace BlockFetch client.
TraceBlockFetchClient: True

# Trace BlockFetch decisions made by the BlockFetch client.
TraceBlockFetchDecisions: True

# Trace BlockFetch protocol messages.
TraceBlockFetchProtocol: True

# Serialised Trace BlockFetch protocol messages.
TraceBlockFetchProtocolSerialised: True

# Trace BlockFetch server.
TraceBlockFetchServer: True

# Trace BlockchainTime.
TraceBlockchainTime: True

# Verbose tracer of ChainDB
TraceChainDb: True

# Trace ChainSync client.
TraceChainSyncClient: True

# Trace ChainSync server (blocks).
TraceChainSyncBlockServer: True

# Trace ChainSync server (headers).
TraceChainSyncHeaderServer: True

# Trace ChainSync protocol messages.
TraceChainSyncProtocol: True

# Trace DNS Resolver messages.
TraceDNSResolver: True

# Trace DNS Subscription messages.
TraceDNSSubscription: True

# Trace error policy resolution.
TraceErrorPolicy: True

# Trace local error policy resolution.
TraceLocalErrorPolicy: True

# Trace block forging.
TraceForge: True

# Trace Handshake protocol messages.
TraceHandshake: True

# Trace IP Subscription messages.
TraceIpSubscription: True

# Trace local root peers
TraceLocalRootPeers: True

# Trace public root peers
TracePublicRootPeers: True

# Trace peer selection
TracePeerSelection: True

# Debug peer selection
TraceDebugPeerSelection: True

# Trace peer selection actions (demotion / promotion between cold / warm and
# hot peers).
TracePeerSelectionActions: True

# Trace connection manager
TraceConnectionManager: True

# Trace server
TraceServer: True

# Trace local connection manager
TraceLocalConnectionManager: True

# Trace local server
TraceLocalServer: True

# Trace local ChainSync protocol messages.
TraceLocalChainSyncProtocol: True

# Trace local Handshake protocol messages.
TraceLocalHandshake: True

# Trace local TxSubmission protocol messages.
TraceLocalTxSubmissionProtocol: True

# Trace local TxSubmission server.
TraceLocalTxSubmissionServer: True

# Trace mempool.
TraceMempool: True

# Trace Mux Events.
TraceMux: False

# Trace TxSubmission server (inbound transactions).
TraceTxInbound: True

# Trace TxSubmission client (outbound transactions).
TraceTxOutbound: True

# Trace TxSubmission protocol messages.
TraceTxSubmissionProtocol: True


##### Fine grained logging control #####

# It is also possible to have more fine grained control over filtering of
# trace output, and to match and route trace output to particular backends.
# This is less efficient than the coarse trace filters above but provides
# much more precise control.

options:

  # This routes metrics matching specific names to particular backends.
  # This overrides the 'defaultBackends' listed above. And note that it is
  # an override and not an extension so anything matched here will not
  # go to the default backend, only to the explicitly listed backends.
  mapBackends:
    cardano.node.metrics:
      - EKGViewBK
    cardano.node.resources:
      - EKGViewBK
    cardano.node.metrics.connectedPeers:
      - EKGViewBK
    cardano.node.ChainDB.metrics:
      - EKGViewBK
    cardano.node.Forge.metrics:
      - EKGViewBK

  # redirects traced values to a specific scribe which is identified by its
  # type and its name, separated by "::":
#  mapScribes:
#    cardano.node.metrics:
#      - "FileSK::logs/mainnet.log"

  # apply a filter on message severity on messages in a specific named context.
  # this filter is applied additionally to the global 'minSeverity' and thus
  # needs to be at least as high.
  mapSeverity:
    cardano.node.ChainDB: Notice
    cardano.node.DnsSubscription: Debug

# P2P

#  # Legacy setting, disabling
#  TestEnableDevelopmentNetworkProtocols: True
EnableP2P: True
#  # The maximum number of used peers during bulk sync.
#  MaxConcurrencyBulkSync: 2
#  # The maximum number of used peers when fetching newly forged blocks.
#  MaxConcurrencyDeadline: 2
TargetNumberOfRootPeers: 10
TargetNumberOfKnownPeers: 100
TargetNumberOfEstablishedPeers: 40
TargetNumberOfActivePeers: 20
TraceInboundGovernorCounters: True
TraceConnectionManagerTransitions: True
TraceLedgerPeers: True
TracePeerSelectionCounters: True
TracePeerStateActions: True
#  # Trace public root peers
#  TracePublicRootPeers: True
#  # Trace BlockFetch decisions made by the BlockFetch client.
#  TraceBlockFetchDecisions: True
#  Trace mempool.
#  TraceMempool: True
